############################ Default configuration #########################
baseURL = "/"
languageCode = "en-us"
# site title 
title = "Mental Health Matters"
# theme
theme = "northendlab"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


########################### Navigation ###################################

# main menu

[[menu.main]]
URL = "information"
name = "Information"
weight = 1

[[menu.main]]
URL = "resources"
name = "Resources"
weight = 2

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3

# footer menu

[[menu.footer]]
URL = "information"
name = "Information"
weight = 1

[[menu.footer]]
URL = "resources"
name = "Resources"
weight = 2

[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 3


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo.svg"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = false


####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Mental Health Matters:<br>Ohio State's mental wellness club."
image = "images/banner/beKindToYaMind.png"


######################## call to action ###############################
[params.cta]
enable = true
image = "images/hugo-muscot.svg"
title = "Join our organization"
description = "Lorem ipsum."
[params.cta.button]
enable = true
label = "Join Us"
link = "https://docs.google.com/forms/d/e/1FAIpQLSfHCA5VtFMvgDY3QYthflSjJXC9S2mpPFStJN6OguZ16Y6lGg/viewform"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "#"