baseURL = "/"
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab"
title = "Mental Health Matters"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
contact_form_action = "#"
home = "Home"
logo = "images/logo.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/beKindToYaMind.png"
info = "Ohio State's mental wellness club."
title = "Mental Health Matters"
[params.cta]
description = "Please fill out this form to get in touch with us."
enable = true
image = "images/loveYa.png"
title = "Join our organization"
[params.cta.button]
enable = true
label = "Join Us"
link = "https://docs.google.com/forms/d/e/1FAIpQLSfHCA5VtFMvgDY3QYthflSjJXC9S2mpPFStJN6OguZ16Y6lGg/viewform"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/mentalhealthmattersosu/"
[[params.social]]
icon = "ti-twitter"
link = "https://twitter.com/mhm_osu"
[permalinks]
pages = ":title"
[taxonomies]
category = "categories"